### ISSUE TITLE
Not working with X-pack

### ISSUE THREAD

**Issue by Anderssorby** [blacktop/docker-kibana-alpine#9]
It seems there is a problem with running this image with the corresponding elasticsearch image with x-pack activated. 

## Using this docker-compose.yml does not work
```yaml
elasticsearch:
    image: blacktop/elasticsearch:7.5
    container_name: elasticsearch
    hostname: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - flex
  kibana:
    image: blacktop/kibana:7.5
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    networks:
      - flex
    depends_on:
      - elasticsearch

```
## Gives this error
```
:["warning","plugins","licensing"],"pid":6,"message":"License information could not be obtained from Elasticsearch for the [data] cluster. [invalid_index_name_exception] Invalid index name [_xpack], must not start with '_'., with { index_uuid=\"_na_\" & index=\"_xpack\" } :: {\"path\":\"/_xpack\",\"statusCode\":400,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"invalid_index_name_exception\\\",\\\"reason\\\":\\\"Invalid index name [_xpack], must not start with '_'.\\\",\\\"index_uuid\\\":\\\"_na_\\\",\\\"index\\\":\\\"_xpack\\\"}],\\\"type\\\":\\\"invalid_index_name_exception\\\",\\\"reason\\\":\\\"Invalid index name [_xpack], must not start with '_'.\\\",\\\"index_uuid\\\":\\\"_na_\\\",\\\"index\\\":\\\"_xpack\\\"},\\\"status\\\":400}\"}"}
```
and
```
FATAL  [mapper_parsing_exception] No handler for type [flattened] declared on field [state] :: {"path":"/.kibana_1","query":{},"b
```

**Comment by Anderssorby** [comment]
However this works fine:
```yaml
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    env_file:
      - ./.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - flex
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    networks:
      - flex
    depends_on:
      - elasticsearch
```

**Comment by blacktop** [comment]
How is your networks defined

**Comment by blacktop** [comment]
```yml
version: "3.7"
services:
  elasticsearch:
    image: blacktop/elasticsearch:7.5.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
    - default

  kibana:
    image: blacktop/kibana:7.5.1
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    networks:
    - default

networks:
  default:
```
